package com.thegs.dsapp.model;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.ParseException;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import javax.xml.transform.stream.StreamSource;

import org.apache.commons.io.FileUtils;
import org.w3c.dom.Document;
import org.xml.sax.SAXException;

import com.thegs.dsapp.model.helper.MarketData;

@XmlRootElement
public class Event {
    private String id;
    private MarketData md;
	private String xmlString;
	
	private String resourcesFolder = System.getProperty("catalina.home") + "/webapps/ROOT/cs9322ass1/";
	private String xmlURI;
	private String xsdPath = resourcesFolder;

    public Event(){

    }
    public Event (String id) throws FileNotFoundException, ParseException{
        this.id = id;
        this.md = new MarketData(id);
        this.xmlURI = ""; 
    }

    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }
	public MarketData getMD() {
		return md;
	}
	public void setMD(MarketData md) {
		this.md = md;
	}
	
	private String makeXML() {
		String ans = "<Response>";
		for (MarketData mdata: md.getMd()) {
			ans += "<Record>";
			
			ans += "<RIC>";
			ans += mdata.getSec();
			ans += "</RIC>";
			
			ans += "<Date>";
			ans += mdata.getDate();
			ans += "</Date>";
			
			ans += "<Time>";
			ans += mdata.getTime();
			ans += "</Time>";
			
			ans += "<GMT>";
			ans += mdata.getGmtOffset();
			ans += "</GMT>";
			
			ans += "<Type>";
			ans += mdata.getType();
			ans += "</Type>";
			
			ans += "<Price>";
			ans += mdata.getPrice();
			ans += "</Price>";
			
			ans += "<Volume>";
			ans += mdata.getVolume();
			ans += "</Volume>";
			
			ans += "<BidPrice>";
			ans += mdata.getBidPrice();
			ans += "</BidPrice>";
			
			ans += "<BidSize>";
			ans += mdata.getBidSize();
			ans += "</BidSize>";
			
			ans += "<AskPrice>";
			ans += mdata.getAskPrice();
			ans += "</AskPrice>";
			
			ans += "<AskSize>";
			ans += mdata.getAskSize();
			ans += "</AskSize>";
			
			ans += "</Record>";
		}
		ans += "</Response>";
		
		return ans;
		
	}
	
	public boolean createXMLFile() throws IOException {
		if (!xmlURI.equals(resourcesFolder + id + ".xml")) {
			xmlString = this.makeXML();
			
			File outputFile = new File(resourcesFolder + id + ".xml");
			FileUtils.writeStringToFile(outputFile, md.stringify());
			
			xmlURI = resourcesFolder + id + ".xml";
			return true;
		} else {
			return false;
		}
	}
	
	public String getXML() {
		return xmlString;
	}
	
	public String convert(String xsd) {
    	
    	DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
    	String fileXML = xmlURI;
    	String fileXSD = xsdPath  + "/" + xsd + ".xsd";
    	String ans = null;
        
    	try {
            
            File stylesheet = new File(fileXSD);
            File datafile = new File(fileXML);

            DocumentBuilder builder = factory.newDocumentBuilder();
            Document document = builder.parse(datafile);
            
            TransformerFactory tFactory = TransformerFactory.newInstance();
            StreamSource stylesource = new StreamSource(stylesheet); 
            Transformer transformer = tFactory.newTransformer(stylesource);

            DOMSource source = new DOMSource(document);
            StreamResult result = new StreamResult(ans);
            transformer.transform(source, result);
            
            return ans;
        } catch (TransformerConfigurationException tce) {
            // Error generated by the parser
            System.out.println("\n** Transformer Factory error");
            System.out.println("   " + tce.getMessage());

            // Use the contained exception, if any
            Throwable x = tce;

            if (tce.getException() != null) {
                x = tce.getException();
            }

            x.printStackTrace();
        } catch (TransformerException te) {
            // Error generated by the parser
            System.out.println("\n** Transformation error");
            System.out.println("   " + te.getMessage());

            // Use the contained exception, if any
            Throwable x = te;

            if (te.getException() != null) {
                x = te.getException();
            }

            x.printStackTrace();
        } catch (SAXException sxe) {
            // Error generated by this application
            // (or a parser-initialization error)
            Exception x = sxe;

            if (sxe.getException() != null) {
                x = sxe.getException();
            }

            x.printStackTrace();
        } catch (ParserConfigurationException pce) {
            // Parser with specified options can't be built
            pce.printStackTrace();
        } catch (IOException ioe) {
            // I/O error
            ioe.printStackTrace();
        }
		return ans;
    }
    
}
